### ISSUE TITLE
v0.1 API Upgrade

### ISSUE THREAD

**Issue by amilstead** [PennyLaneAI/PennyLane-IonQ#23]
Hi there!

IonQ's `v0` API is currently deprecated. It would be great if we could get the Pennylane provider updated to use the `v0.1` version.

I wanted to open an issue here first just in case this was already on a road map or in active development.

Depending on timing, we may be able to submit a PR for the upgrade ourselves.

**Comment by co9olguy** [comment]
Hi @amilstead, thanks for the request!

As I understand it from the IonQ docs, the only changes from `v0` to `v1` involve 
- cancelling of jobs,
- deletion of jobs, or
- bulk requests
Since we don't currently make use of any of these endpoints in the plugin, upgrading to `v1` would be as simple as updating [this file](https://github.com/PennyLaneAI/PennyLane-IonQ/blob/ce8e0be0f502e6d16586b696a393999cb0a34e7f/pennylane_ionq/api_client.py), with the change `v0`-->`v1`? Is this all you're seeking at the moment?

If so, that's a pretty straightforward request and we can easily accommodate it. If you're thinking of something broader, please do share some more info

**Comment by amilstead** [comment]
> ... upgrading to `v1` would be as simple as updating [this file](https://github.com/PennyLaneAI/PennyLane-IonQ/blob/ce8e0be0f502e6d16586b696a393999cb0a34e7f/pennylane_ionq/api_client.py), with the change `v0`-->`v1`?
> 

That's pretty much it (though it would be `v0` --> `v0.1`, not `v1`)!

The only other notable difference between the `v0` and `v0.1` job response is that the root-level `script` attribute (which echoes the script/circuit used to create a job) has been removed from the response. We will likely surface this data again in the future under a different endpoint. Until then, the client will be responsible for storing this information as needed.

Also, looking through the `api_client` module, the `JobResult` and `JobCircuit` classes appear to use `v0/jobs/{job_id}/data` and `v0/jobs/{job_id}/circuit`. If those map to URL paths used to access the API, I'm afraid we have no such endpoints. That said, I may just be misunderstanding what happens with `PATH` attributes before requests are made but figured I'd surface just in case!
